import { buildSample } from "../src/lib/sample";
import { comingUp, ageWindowLabel, relevance, byAgeFit } from "../src/lib/milestones";
import { MILESTONE_CATALOG, MILESTONE_DEFS } from "../src/lib/types";
import { milestonesLogged, heightSeries, weightSeries } from "../src/lib/selectors";
let fails = 0; const ok = (n: string, c: boolean) => { console.log(c ? "PASS" : "FAIL", n); if (!c) fails++; };
ok("age labels", ageWindowLabel([5, 8]) === "5–8 months" && ageWindowLabel([24, 36]) === "2–3 years" && ageWindowLabel([20, 30]) === "20 months–2.5 years");
const found = (id: string) => MILESTONE_CATALOG.find((d) => d.id === id)!;
ok("relevance (Rolls is a 6–12 month milestone)", relevance(found("mov-rolls"), 8) === 0 && relevance(found("mov-rolls"), 4) === 2 && relevance(found("mov-rolls"), 14) === 2);
const cu = comingUp(MILESTONE_CATALOG, (id) => id === "lang-babbles", 7, 12).map((d) => d.id);
ok("coming up at 7 months: the 6–12 stage, not what is already ticked or what is far off", cu.includes("mov-sits") && cu.includes("mov-crawls") && !cu.includes("lang-babbles") && !cu.includes("mov-walks"));
ok("age fit order", byAgeFit(MILESTONE_CATALOG, 7)[0].months![0] <= 7 && byAgeFit(MILESTONE_CATALOG, 7)[0].months![1] >= 7);
const s = buildSample();
ok("sample: ONE list holds every type", ["photo", "story", "milestone", "first", "last", "measure"].every((t) => s.memories.some((m) => m.type === t)));
ok("sample: nothing has old-format fields", s.memories.every((m: any) => m.caption === undefined && m.uri === undefined && m.entryKind === undefined && m.people === undefined && m.tags === undefined));
ok("sample: every memory has the common fields", s.memories.every((m) => m.id && m.childId && m.type && typeof m.description === "string" && m.date && Array.isArray(m.media) && Array.isArray(m.tagIds) && typeof m.createdAt === "number"));
ok("sample: ids unique", new Set(s.memories.map((m) => m.id)).size === s.memories.length);
const maya = milestonesLogged(s.memories, "maya");
ok("sample: milestones are memories pointing at real catalogue entries", Object.keys(maya).length === 7 && Object.keys(maya).every((id) => MILESTONE_DEFS.some((d) => d.id === id)) && maya["mov-crawls"].title === "Crawls or scoots" && !!maya["pulls-to-stand"]);
ok("sample: heights and weights come from measurement memories", heightSeries(s.memories, "maya").length === 7 && weightSeries(s.memories, "maya").length === 7 && heightSeries(s.memories, "leo")[2].cm === 65.5);
ok("sample: avatar memories exist; nothing before birth", s.kids.every((k) => s.memories.some((m) => m.id === k.avatarPhotoId)) && s.memories.every((m) => m.date >= s.kids.find((k) => k.id === m.childId)!.birth));
ok("sample: every tag id on a memory is in the central list", s.memories.every((m) => m.tagIds.every((id) => s.tags.some((t) => t.id === id))));
console.log(fails ? `${fails} FAILED` : "all milestone/sample tests passed");
