import { normalizeShared, parseVideoDate, summarize } from "../src/lib/sharedMedia";
let fails = 0; const ok = (n: string, c: boolean) => { console.log(c ? "PASS" : "FAIL", n); if (!c) fails++; };
const photo = normalizeShared({ uri: "/data/x/shared-1.jpg", mime: "image/jpeg", name: "IMG_1234.jpg", size: 1, exif: "2024:03:15 10:15:42" });
ok("photo: original EXIF date AND time kept", photo.kind === "photo" && photo.date === "2024-03-15" && photo.time === "10:15" && photo.uri === "file:///data/x/shared-1.jpg");
const noTime = normalizeShared({ uri: "file:///a.jpg", mime: "image/jpeg", name: "scan.jpg", size: 1, exif: "2024:03:15 00:00:00" });
ok("midnight-only EXIF has a date but no made-up time", noTime.date === "2024-03-15" && noTime.time === undefined);
const named = normalizeShared({ uri: "file:///b.jpg", mime: "image/jpeg", name: "PXL_20230612_164501234.jpg", size: 1, exif: null });
ok("no EXIF → date from the camera's file name", named.date === "2023-06-12" && named.time === undefined);
const wa = normalizeShared({ uri: "file:///c.jpg", mime: "image/jpeg", name: "IMG-20220101-WA0007.jpg", size: 1 });
ok("WhatsApp-style names work too", wa.date === "2022-01-01");
const none = normalizeShared({ uri: "file:///d.jpg", mime: "image/jpeg", name: "download (3).jpg", size: 1, exif: "0000:00:00 00:00:00" });
ok("nothing usable → no date (the import screen falls back and says so)", none.date === undefined && none.time === undefined);
const future = normalizeShared({ uri: "file:///e.jpg", mime: "image/jpeg", name: "x.jpg", size: 1, exif: "2099:01:01 10:00:00" });
const ancient = normalizeShared({ uri: "file:///f.jpg", mime: "image/jpeg", name: "x.jpg", size: 1, exif: "1970:01:01 00:00:00" });
ok("implausible dates (future / 1970) are ignored", future.date === undefined && ancient.date === undefined);
const v = normalizeShared({ uri: "file:///g.mp4", mime: "video/mp4", name: "VID_1.mp4", size: 9, videoDate: "20240315T101500.000Z" });
const local = parseVideoDate("20240315T101500.000Z")!;
ok("video: recording date from metadata, converted to local time", v.kind === "video" && v.date === local.date && v.time === local.time && /^\d{4}-\d{2}-\d{2}$/.test(v.date!));
ok("video with no metadata falls back to the file name", normalizeShared({ uri: "file:///h.mp4", mime: "video/mp4", name: "VID_20210704_120000.mp4", size: 1 }).date === "2021-07-04");
ok("bad video date is ignored", parseVideoDate("garbage") === null && parseVideoDate(undefined) === null);
const fmt = (s: string) => s;
ok("summary: counts and the date range", summarize([photo, named, v].map((x) => ({ ...x, date: x === photo ? "2024-03-15" : x === named ? "2024-03-17" : "2024-03-15" })), fmt) === "2 photos · 1 video · taken 2024-03-15 – 2024-03-17");
ok("summary: one day, and none", summarize([photo], fmt) === "1 photo · taken 2024-03-15" && summarize([none], fmt) === "1 photo");
console.log(fails ? `${fails} FAILED` : "all shared-media tests passed");
